title: Decentra Vision - On-chain Security
description: Offering my services as an independent smart contract security researcher
theme: just-the-docs

url: https://decentra.vision

nav_external_links:
  - title: Get a quote
    url: https://tally.so/r/3lOGb6
    hide_icon: false
    opens_in_new_tab: true
  - title: Public reports
    url: https://github.com/MarioPoneder/audits
    hide_icon: false
    opens_in_new_tab: true
  - title: FindAudit profile
    url: https://findaudit.decentra.vision/
    hide_icon: false
    opens_in_new_tab: true
  
logo: "img/logo_dark.png"

heading_anchors: false

color_scheme: custom_dark

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.0"
