title: Decentra Vision
description: Decentra Vision - On-chain Security | Offering my services as an independent smart contract security researcher 
theme: just-the-docs

url: https://decentra.vision/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

heading_anchors: false

color_scheme: dark

