title: Decentra Vision
description: Decentra Vision - On-chain Security | Offering my services as an independent smart contract security researcher 
theme: just-the-docs

url: https://decentra.vision/

nav_external_links:
  - title: Public Reports
    url: https://github.com/MarioPoneder/audits
    hide_icon: false
    opens_in_new_tab: true
  
logo: "img/logo_dark.png"

heading_anchors: false

color_scheme: dark

