title: Decentra Vision
description: Decentra Vision - On-chain Security | Offering my services as an independent smart contract security researcher 
theme: just-the-docs

url: https://decentra.vision/

aux_links:
  View Public Reports: https://github.com/MarioPoneder/audits
  
#logo: "img/logo.png"

heading_anchors: false

color_scheme: light

